dataPlaneIp: "127.0.0.1"
controlPlaneIp: "localhost"
controlPlanePort: "9090"
portProxy: "8080"
portGRPC: "8081"
portProxyRead: "8082"
verbosity: "trace"
traceOutputFolder: "data"
loadBalancingPolicy: "random"
async: true
persistRequests: false

redis:
  address: "127.0.0.1:6379"
  password: ""
  db: 0
  fullPersistence: false