dataPlaneIp: "dynamic"
controlPlaneAddress: "10.0.1.2:9090"
portProxy: "8080"
portProxyRead: "8082"
portGRPC: "8081"
verbosity: "trace"
traceOutputFolder: "data"
loadBalancingPolicy: "knative"
async: true
persistRequests: true
numberRetries: 3

redis:
  address: "10.0.1.1:6379"
  password: ""
  db: 0
  fullPersistence: false