dataPlaneIp: "127.0.0.1"
controlPlaneAddress: "127.0.0.1:9090,127.0.0.1:10000,127.0.0.1:10001"
portProxy: "11080"
portGRPC: "11081"
portProxyRead: "11082"
verbosity: "trace"
traceOutputFolder: "data"
loadBalancingPolicy: "random"
workflowDefaultScheduler: "concurrentFifo"
workflowPreferredWorkerParallelism: 4
async:
  enabled: false
  persistRequests: false
  numberRetries: 3
  requestBufferSize: 1000

redis:
  address: "127.0.0.1:6379"
  replicas: ""
  password: ""
  db: 0
  fullPersistence: false

controlPlaneNotifyIntervalMinutes: 15