dataPlaneIp: "dynamic"
controlPlaneIp: "10.0.1.2"
controlPlanePort: "9090"
portProxy: "8080"
portProxyRead: "8082"
portGRPC: "8081"
verbosity: "trace"
traceOutputFolder: "data"
loadBalancingPolicy: "knative"
async: false
persistRequests: false

redis:
  address: "10.0.1.1:6379"
  password: ""
  db: 0
  fullPersistence: false