controlPlaneIp: "10.0.1.2"
controlPlanePort: "9090"
port: "10010"
verbosity: "trace"
criType: "firecracker"
criPath: "/run/containerd/containerd.sock"
cniConfigPath: "../../configs/cni.conf"
prefetchImage: false

firecrackerKernel: "/home/lcvetkovic/projects/cluster_manager/configs/firecracker/vmlinux.bin"
firecrackerFileSystem: "/home/lcvetkovic/projects/cluster_manager/configs/firecracker/rootfs.ext4"
firecrackerIPPrefix: "169.254"