workerNodeIp: "127.0.0.1"
controlPlaneAddress: "127.0.0.1:9090"
port: "10010"
verbosity: "trace"
criType: "firecracker"
cpuConstraints: false

containerd:
  criPath: "/run/containerd/containerd.sock"
  cniConfigPath: "configs/cni.conf"
  prefetchImage: false

firecracker:
  Kernel: "configs/firecracker/vmlinux-4.14.bin"
  FileSystem: "configs/firecracker/rootfs_cpp.ext4"
  InternalIPPrefix: "100"
  VMDebugMode: false
  UseSnapshots: true
  NetworkPoolSize: 4

dandelion:
  daemonPort: 8082
  binaryPath: "configs/dandelion/sysld_wasm_x86_64_busy_loop"
  engineType: "Process"
  #binaryPath: "configs/dandelion/sysld_wasm_x86_64_matmul"
  #engineType: "RWasm"
  logFunctionStdioOutset: false
