workerNodeIp: "127.0.0.1"
controlPlaneAddress: "127.0.0.1:9090"
port: "10010"
verbosity: "trace"
criType: "containerd"
cpuConstaint: false

containerd:
  criPath: "/run/containerd/containerd.sock"
  cniConfigPath: "configs/cni.conf"
  prefetchImage: false

firecracker:
  Kernel: "configs/firecracker/vmlinux-4.14.bin"
  FileSystem: "configs/firecracker/rootfs.ext4"
  InternalIPPrefix: "100"
  ExposedIPPrefix: "192.254"
  VMDebugMode: false
  UseSnapshots: true
  NetworkPoolSize: 128