workerNodeIp: "dynamic"
controlPlaneIp: "10.0.1.2"
controlPlanePort: "9090"
port: "10010"
verbosity: "trace"
criType: "firecracker"
criPath: "/run/containerd/containerd.sock"
cniConfigPath: "configs/cni.conf"
prefetchImage: false

firecrackerKernel: "configs/firecracker/vmlinux-4.14.bin"
firecrackerFileSystem: "configs/firecracker/rootfs.ext4"
firecrackerInternalIPPrefix: "10"
firecrackerExposedIPPrefix: "192.254"
firecrackerVMDebugMode: false
firecrackerUseSnapshots: true