workerNodeIp: "127.0.0.1"
controlPlaneIp: "localhost"
controlPlanePort: "9090"
port: "10010"
verbosity: "trace"
criType: "firecracker"
criPath: "/run/containerd/containerd.sock"
cniConfigPath: "configs/cni.conf"
prefetchImage: false

firecrackerKernel: "configs/firecracker/vmlinux.bin"
firecrackerFileSystem: "configs/firecracker/rootfs.ext4"
firecrackerIPPrefix: "169.254"
firecrackerVMDebugMode: false