controlPlaneIp: "localhost"
controlPlanePort: "9090"
port: "10010"
verbosity: "trace"
criType: "containerd"
criPath: "/run/containerd/containerd.sock"
cniConfigPath: "configs/cni.conf"
prefetchImage: true