workerNodeIp: "dynamic"
controlPlaneAddress: "10.0.1.2:9090,10.0.1.3:10000,10.0.1.4:10001"
port: "$DAEMON_PORT"
verbosity: "trace"
criType: "scalability_test"

containerd:
  criPath: "/run/containerd/containerd.sock"
  cniConfigPath: "configs/cni.conf"
  prefetchImage: false

firecracker:
  Kernel: "/cluster_manager/configs/firecracker/vmlinux-4.14.bin"
  FileSystem: "/cluster_manager/configs/firecracker/rootfs.ext4"
  InternalIPPrefix: "100"
  ExposedIPPrefix: "192.254"
  VMDebugMode: false
  UseSnapshots: true
  NetworkPoolSize: 128