port: "9090"
replicas: ""
registrationServer: "127.0.0.1:9091"
registrationServerReplicas: ""
verbosity: "debug"
traceOutputFolder: "data"
placementPolicy: "random"
persistence: false
reconstruct: false

# to use HAProxy load balancer put 127.0.0.1:8079, otherwise leave blank
loadBalancerAddress: "127.0.0.1:8079"

removeWorkerNode: false
removeDataplane: false

precreateSnapshots: false

profiler:
  enable: false
  mutex: false

redis:
  address: "127.0.0.1:6379"
  dockerAddress: "127.0.0.1:6379"
  password: ""
  db: 0
  fullPersistence: true
