port: "10000"
replicas: "10.0.1.2:9090,10.0.1.4:10001"
portRegistration: "9091"
verbosity: "debug"
traceOutputFolder: "data"
placementPolicy: "random"
persistence: true
reconstruct: true

loadBalancerAddress: ""

removeWorkerNode: false
removeDataplane: false

precreateSnapshots: false

profiler:
  enable: false
  mutex: false

redis:
  address: "10.0.1.3:6379"
  dockerAddress: "10.0.1.3:6379"
  replicas: "10.0.1.2:6379,10.0.1.4:6379"
  password: ""
  db: 0
  fullPersistence: false
