port: "9090"
portRegistration: "9091"
verbosity: "trace"
traceOutputFolder: "data"
placementPolicy: "round-robin"
persistence: false
reconstruct: false

removeWorkerNode: false
removeDataplane: false

traceCreation: false
precreateSnapshots: true

profiler:
  enable: false
  mutex: false

redis:
  address: "10.0.1.1:6379"
  password: ""
  db: 0
  fullPersistence: false