port: "10001"
replicas: "127.0.0.1:9090,127.0.0.1:10000"
registrationServer: "127.0.0.1:15091"
registrationServerReplicas: "127.0.0.1:13091,127.0.0.1:14091"
verbosity: "trace"
traceOutputFolder: "data"
placementPolicy: "random"
persistence: true
reconstruct: true

# to use HAProxy load balancer put 127.0.0.1:8079, otherwise leave blank
loadBalancerAddress: "127.0.0.1:8079"

removeWorkerNode: false
removeDataplane: false

precreateSnapshots: false

profiler:
  enable: false
  mutex: false

redis:
  address: "127.0.0.1:6382"
  dockerAddress: "redis_3:6379"
  replicas: "127.0.0.1:6380,127.0.0.1:6381"
  password: ""
  db: 0
  fullPersistence: true

endpointPersistence: false