port: "9090"
replicas: ""
portRegistration: "9091"
verbosity: "debug"
traceOutputFolder: "data"
placementPolicy: "random"
persistence: false
reconstruct: false

removeWorkerNode: false
removeDataplane: false

precreateSnapshots: false

profiler:
  enable: false
  mutex: false

redis:
  address: "10.0.1.1:6379"
  replicas: ""
  password: ""
  db: 0
  fullPersistence: false