port: "9090"
replicas: "127.0.0.1:10000,127.0.0.1:10001"
portRegistration: "9091"
verbosity: "debug"
traceOutputFolder: "data"
placementPolicy: "random"
persistence: true
reconstruct: true

removeWorkerNode: false
removeDataplane: false

precreateSnapshots: false

profiler:
  enable: false
  mutex: false

redis:
  address: "127.0.0.1:6379"
  password: ""
  db: 0
  fullPersistence: false
