port: "9090"
portRegistration: "9091"
verbosity: "trace"
traceOutputFolder: "data"
placementPolicy: "random"
persistence: false
reconstruct: false

removeWorkerNode: true
removeDataplane: true

profiler:
  enable: false
  mutex: false

redis:
  address: "127.0.0.1:6379"
  password: ""
  db: 0
  fullPersistence: false
