port: "9090"
replicas: "127.0.0.1:10000,127.0.0.1:10001"
registrationServer: "127.0.0.1:13091"
registrationServerReplicas: "127.0.0.1:14091,127.0.0.1:15091"
verbosity: "trace"
traceOutputFolder: "data"
placementPolicy: "random"
persistence: true
reconstruct: true
autoscaler: "default"
autoscalingPeriod: "2s"
defaultWFPartitionMethod: "fullPartition"
imageStorage: "default"
cidr: "100.22.0.0/16"

# to use HAProxy load balancer put 127.0.0.1:8079, otherwise leave blank
loadBalancerAddress: "127.0.0.1:8079"

removeWorkerNode: false
removeDataplane: false

precreateSnapshots: false

redis:
  address: "127.0.0.1:6380"
  addressFromDockerNetwork: "redis_1:6379"
  replicas: "127.0.0.1:6381,127.0.0.1:6382"
  password: ""
  db: 0
  fullPersistence: true
