port: "9090"
replicas: ""
registrationServer: "10.0.1.2:9091"
verbosity: "debug"
traceOutputFolder: "data"
placementPolicy: "random"
persistence: false
reconstruct: false

# to use HAProxy load balancer put 10.0.1.254:8079, otherwise leave blank
loadBalancerAddress: "10.0.1.254:8079"

removeWorkerNode: false
removeDataplane: false

precreateSnapshots: false

profiler:
  enable: false
  mutex: false

redis:
  address: "10.0.1.1:6379"
  replicas: ""
  password: ""
  db: 0
  fullPersistence: false