port: "10000"
replicas: "10.0.1.2:9090,10.0.1.4:10001"
registrationServer: "10.0.1.3:9091"
registrationServerReplicas: "10.0.1.2:9091,10.0.1.4:9091"
verbosity: "trace"
traceOutputFolder: "data"
placementPolicy: "random"
persistence: true
reconstruct: true
autoscaler: "default"
autoscalingPeriod: "2s"
defaultWFPartitionMethod: "fullPartition"
imageStorage: "default"

# to use HAProxy load balancer put 10.0.1.254:8079, otherwise leave blank
loadBalancerAddress: "10.0.1.254:8079"

removeWorkerNode: false
removeDataplane: false

precreateSnapshots: false

redis:
  address: "10.0.1.3:6379"
  addressFromDockerNetwork: "10.0.1.3:6379"
  replicas: "10.0.1.2:6379,10.0.1.4:6379"
  password: ""
  db: 0
  fullPersistence: true
