port: "9090"
replicas: ""
registrationServer: "127.0.0.1:9091"
registrationServerReplicas: ""
verbosity: "trace"
traceOutputFolder: "data"
placementPolicy: "random"
persistence: false
reconstruct: false
autoscaler: "default"
autoscalingPeriod: "2s"

# to use HAProxy load balancer put 127.0.0.1:8079, otherwise leave blank
loadBalancerAddress: "127.0.0.1:8079"

removeWorkerNode: false
removeDataplane: false

precreateSnapshots: false

redis:
  address: "127.0.0.1:6379"
  addressFromDockerNetwork: "127.0.0.1:6379"
  password: ""
  db: 0
  fullPersistence: true

endpointPersistence: false