port: "10001"
replicas: "127.0.0.1:9090,127.0.0.1:10000"
portRegistration: "9091"
verbosity: "debug"
traceOutputFolder: "data"
placementPolicy: "random"
persistence: false
reconstruct: false

removeWorkerNode: false
removeDataplane: false

traceCreation: true
precreateSnapshots: false

profiler:
  enable: false
  mutex: false

redis:
  address: "127.0.0.1:6379"
  password: ""
  db: 0
  fullPersistence: false
