port: "9090"
portRegistration: "9091"
verbosity: "trace"
traceOutputFolder: "data"
placementPolicy: "kubernetes"
persistence: false
reconstruct: false

removeWorkerNode: false
removeDataplane: false

precreateSnapshots: false

profiler:
  enable: true
  mutex: false

redis:
  address: "10.0.1.1:6379"
  password: ""
  db: 0
  fullPersistence: false