port: "10001"
replicas: "127.0.0.1:9090,127.0.0.1:10000"
portRegistration: "9091"
verbosity: "debug"
traceOutputFolder: "data"
placementPolicy: "random"
persistence: true
reconstruct: true

loadBalancerAddress: ""

removeWorkerNode: false
removeDataplane: false

precreateSnapshots: false

profiler:
  enable: false
  mutex: false

redis:
  address: "127.0.0.1:6382"
  dockerAddress: "redis_3:6379"
  replicas: "127.0.0.1:6380,127.0.0.1:6381"
  password: ""
  db: 0
  fullPersistence: false
