port: "9090"
replicas: "127.0.0.1:10000,127.0.0.1:10001"
registrationServer: "127.0.0.1:9091"
verbosity: "debug"
traceOutputFolder: "data"
placementPolicy: "random"
persistence: true
reconstruct: true

# to use HAProxy load balancer put 127.0.0.1:8079, otherwise leave blank
loadBalancerAddress: ""

removeWorkerNode: false
removeDataplane: false

precreateSnapshots: false

profiler:
  enable: false
  mutex: false

redis:
  address: "127.0.0.1:6380"
  dockerAddress: "redis_1:6379"
  replicas: "127.0.0.1:6381,127.0.0.1:6382"
  password: ""
  db: 0
  fullPersistence: false
