port: "9090"
portRegistration: "9091"
verbosity: "trace"
traceOutputFolder: "data"
placementPolicy: "random"
persistence: true
reconstruct: false


profiler:
  enable: true
  mutex: false

redis:
  address: "10.0.1.1:6379"
  password: ""
  db: 0
  fullPersistence: true