package predictive_autoscaler

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Decider) DeepCopyInto(out *Decider) {
	*out = *in
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Decider.
func (in *Decider) DeepCopy() *Decider {
	if in == nil {
		return nil
	}
	out := new(Decider)
	in.DeepCopyInto(out)
	return out
}
