// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.17.3
// source: data_plane_interface.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DpiInterface_AddDeployment_FullMethodName            = "/data_plane.DpiInterface/AddDeployment"
	DpiInterface_DeleteDeployment_FullMethodName         = "/data_plane.DpiInterface/DeleteDeployment"
	DpiInterface_UpdateDeployment_FullMethodName         = "/data_plane.DpiInterface/UpdateDeployment"
	DpiInterface_AddWorkflowDeployment_FullMethodName    = "/data_plane.DpiInterface/AddWorkflowDeployment"
	DpiInterface_DeleteWorkflowDeployment_FullMethodName = "/data_plane.DpiInterface/DeleteWorkflowDeployment"
	DpiInterface_UpdateEndpointList_FullMethodName       = "/data_plane.DpiInterface/UpdateEndpointList"
	DpiInterface_DrainSandbox_FullMethodName             = "/data_plane.DpiInterface/DrainSandbox"
	DpiInterface_ResetMeasurements_FullMethodName        = "/data_plane.DpiInterface/ResetMeasurements"
)

// DpiInterfaceClient is the client API for DpiInterface service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DpiInterfaceClient interface {
	AddDeployment(ctx context.Context, in *ServiceInfo, opts ...grpc.CallOption) (*DeploymentUpdateSuccess, error)
	DeleteDeployment(ctx context.Context, in *ServiceInfo, opts ...grpc.CallOption) (*DeploymentUpdateSuccess, error)
	UpdateDeployment(ctx context.Context, in *ServiceInfo, opts ...grpc.CallOption) (*DeploymentUpdateSuccess, error)
	AddWorkflowDeployment(ctx context.Context, in *WorkflowInfo, opts ...grpc.CallOption) (*DeploymentUpdateSuccess, error)
	DeleteWorkflowDeployment(ctx context.Context, in *WorkflowObjectIdentifier, opts ...grpc.CallOption) (*DeploymentUpdateSuccess, error)
	UpdateEndpointList(ctx context.Context, in *DeploymentEndpointPatch, opts ...grpc.CallOption) (*DeploymentUpdateSuccess, error)
	DrainSandbox(ctx context.Context, in *DeploymentEndpointPatch, opts ...grpc.CallOption) (*DeploymentUpdateSuccess, error)
	ResetMeasurements(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ActionStatus, error)
}

type dpiInterfaceClient struct {
	cc grpc.ClientConnInterface
}

func NewDpiInterfaceClient(cc grpc.ClientConnInterface) DpiInterfaceClient {
	return &dpiInterfaceClient{cc}
}

func (c *dpiInterfaceClient) AddDeployment(ctx context.Context, in *ServiceInfo, opts ...grpc.CallOption) (*DeploymentUpdateSuccess, error) {
	out := new(DeploymentUpdateSuccess)
	err := c.cc.Invoke(ctx, DpiInterface_AddDeployment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dpiInterfaceClient) DeleteDeployment(ctx context.Context, in *ServiceInfo, opts ...grpc.CallOption) (*DeploymentUpdateSuccess, error) {
	out := new(DeploymentUpdateSuccess)
	err := c.cc.Invoke(ctx, DpiInterface_DeleteDeployment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dpiInterfaceClient) UpdateDeployment(ctx context.Context, in *ServiceInfo, opts ...grpc.CallOption) (*DeploymentUpdateSuccess, error) {
	out := new(DeploymentUpdateSuccess)
	err := c.cc.Invoke(ctx, DpiInterface_UpdateDeployment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dpiInterfaceClient) AddWorkflowDeployment(ctx context.Context, in *WorkflowInfo, opts ...grpc.CallOption) (*DeploymentUpdateSuccess, error) {
	out := new(DeploymentUpdateSuccess)
	err := c.cc.Invoke(ctx, DpiInterface_AddWorkflowDeployment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dpiInterfaceClient) DeleteWorkflowDeployment(ctx context.Context, in *WorkflowObjectIdentifier, opts ...grpc.CallOption) (*DeploymentUpdateSuccess, error) {
	out := new(DeploymentUpdateSuccess)
	err := c.cc.Invoke(ctx, DpiInterface_DeleteWorkflowDeployment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dpiInterfaceClient) UpdateEndpointList(ctx context.Context, in *DeploymentEndpointPatch, opts ...grpc.CallOption) (*DeploymentUpdateSuccess, error) {
	out := new(DeploymentUpdateSuccess)
	err := c.cc.Invoke(ctx, DpiInterface_UpdateEndpointList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dpiInterfaceClient) DrainSandbox(ctx context.Context, in *DeploymentEndpointPatch, opts ...grpc.CallOption) (*DeploymentUpdateSuccess, error) {
	out := new(DeploymentUpdateSuccess)
	err := c.cc.Invoke(ctx, DpiInterface_DrainSandbox_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dpiInterfaceClient) ResetMeasurements(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ActionStatus, error) {
	out := new(ActionStatus)
	err := c.cc.Invoke(ctx, DpiInterface_ResetMeasurements_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DpiInterfaceServer is the server API for DpiInterface service.
// All implementations must embed UnimplementedDpiInterfaceServer
// for forward compatibility
type DpiInterfaceServer interface {
	AddDeployment(context.Context, *ServiceInfo) (*DeploymentUpdateSuccess, error)
	DeleteDeployment(context.Context, *ServiceInfo) (*DeploymentUpdateSuccess, error)
	UpdateDeployment(context.Context, *ServiceInfo) (*DeploymentUpdateSuccess, error)
	AddWorkflowDeployment(context.Context, *WorkflowInfo) (*DeploymentUpdateSuccess, error)
	DeleteWorkflowDeployment(context.Context, *WorkflowObjectIdentifier) (*DeploymentUpdateSuccess, error)
	UpdateEndpointList(context.Context, *DeploymentEndpointPatch) (*DeploymentUpdateSuccess, error)
	DrainSandbox(context.Context, *DeploymentEndpointPatch) (*DeploymentUpdateSuccess, error)
	ResetMeasurements(context.Context, *emptypb.Empty) (*ActionStatus, error)
	mustEmbedUnimplementedDpiInterfaceServer()
}

// UnimplementedDpiInterfaceServer must be embedded to have forward compatible implementations.
type UnimplementedDpiInterfaceServer struct {
}

func (UnimplementedDpiInterfaceServer) AddDeployment(context.Context, *ServiceInfo) (*DeploymentUpdateSuccess, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddDeployment not implemented")
}
func (UnimplementedDpiInterfaceServer) DeleteDeployment(context.Context, *ServiceInfo) (*DeploymentUpdateSuccess, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDeployment not implemented")
}
func (UnimplementedDpiInterfaceServer) UpdateDeployment(context.Context, *ServiceInfo) (*DeploymentUpdateSuccess, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDeployment not implemented")
}
func (UnimplementedDpiInterfaceServer) AddWorkflowDeployment(context.Context, *WorkflowInfo) (*DeploymentUpdateSuccess, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddWorkflowDeployment not implemented")
}
func (UnimplementedDpiInterfaceServer) DeleteWorkflowDeployment(context.Context, *WorkflowObjectIdentifier) (*DeploymentUpdateSuccess, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWorkflowDeployment not implemented")
}
func (UnimplementedDpiInterfaceServer) UpdateEndpointList(context.Context, *DeploymentEndpointPatch) (*DeploymentUpdateSuccess, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEndpointList not implemented")
}
func (UnimplementedDpiInterfaceServer) DrainSandbox(context.Context, *DeploymentEndpointPatch) (*DeploymentUpdateSuccess, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DrainSandbox not implemented")
}
func (UnimplementedDpiInterfaceServer) ResetMeasurements(context.Context, *emptypb.Empty) (*ActionStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetMeasurements not implemented")
}
func (UnimplementedDpiInterfaceServer) mustEmbedUnimplementedDpiInterfaceServer() {}

// UnsafeDpiInterfaceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DpiInterfaceServer will
// result in compilation errors.
type UnsafeDpiInterfaceServer interface {
	mustEmbedUnimplementedDpiInterfaceServer()
}

func RegisterDpiInterfaceServer(s grpc.ServiceRegistrar, srv DpiInterfaceServer) {
	s.RegisterService(&DpiInterface_ServiceDesc, srv)
}

func _DpiInterface_AddDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DpiInterfaceServer).AddDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DpiInterface_AddDeployment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DpiInterfaceServer).AddDeployment(ctx, req.(*ServiceInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _DpiInterface_DeleteDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DpiInterfaceServer).DeleteDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DpiInterface_DeleteDeployment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DpiInterfaceServer).DeleteDeployment(ctx, req.(*ServiceInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _DpiInterface_UpdateDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DpiInterfaceServer).UpdateDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DpiInterface_UpdateDeployment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DpiInterfaceServer).UpdateDeployment(ctx, req.(*ServiceInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _DpiInterface_AddWorkflowDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DpiInterfaceServer).AddWorkflowDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DpiInterface_AddWorkflowDeployment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DpiInterfaceServer).AddWorkflowDeployment(ctx, req.(*WorkflowInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _DpiInterface_DeleteWorkflowDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowObjectIdentifier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DpiInterfaceServer).DeleteWorkflowDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DpiInterface_DeleteWorkflowDeployment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DpiInterfaceServer).DeleteWorkflowDeployment(ctx, req.(*WorkflowObjectIdentifier))
	}
	return interceptor(ctx, in, info, handler)
}

func _DpiInterface_UpdateEndpointList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeploymentEndpointPatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DpiInterfaceServer).UpdateEndpointList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DpiInterface_UpdateEndpointList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DpiInterfaceServer).UpdateEndpointList(ctx, req.(*DeploymentEndpointPatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _DpiInterface_DrainSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeploymentEndpointPatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DpiInterfaceServer).DrainSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DpiInterface_DrainSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DpiInterfaceServer).DrainSandbox(ctx, req.(*DeploymentEndpointPatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _DpiInterface_ResetMeasurements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DpiInterfaceServer).ResetMeasurements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DpiInterface_ResetMeasurements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DpiInterfaceServer).ResetMeasurements(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// DpiInterface_ServiceDesc is the grpc.ServiceDesc for DpiInterface service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DpiInterface_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "data_plane.DpiInterface",
	HandlerType: (*DpiInterfaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddDeployment",
			Handler:    _DpiInterface_AddDeployment_Handler,
		},
		{
			MethodName: "DeleteDeployment",
			Handler:    _DpiInterface_DeleteDeployment_Handler,
		},
		{
			MethodName: "UpdateDeployment",
			Handler:    _DpiInterface_UpdateDeployment_Handler,
		},
		{
			MethodName: "AddWorkflowDeployment",
			Handler:    _DpiInterface_AddWorkflowDeployment_Handler,
		},
		{
			MethodName: "DeleteWorkflowDeployment",
			Handler:    _DpiInterface_DeleteWorkflowDeployment_Handler,
		},
		{
			MethodName: "UpdateEndpointList",
			Handler:    _DpiInterface_UpdateEndpointList_Handler,
		},
		{
			MethodName: "DrainSandbox",
			Handler:    _DpiInterface_DrainSandbox_Handler,
		},
		{
			MethodName: "ResetMeasurements",
			Handler:    _DpiInterface_ResetMeasurements_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data_plane_interface.proto",
}
