# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Configure HAProxy
        run: sudo apt-get update && sudo apt-get install haproxy && sudo cp ./configs/haproxy.cfg /etc/haproxy/haproxy.cfg

      - name: Build
        run: go build -ldflags='-extldflags=-Wl,-z,lazy' ./...

      - name: Test
        run: |
          curl -L -o cni-plugins.tgz https://github.com/containernetworking/plugins/releases/download/v0.8.1/cni-plugins-linux-amd64-v0.8.1.tgz
          sudo mkdir -p /opt/cni/bin
          sudo tar -C /opt/cni/bin -xzf cni-plugins.tgz
          sudo go test -ldflags='-extldflags=-Wl,-z,lazy' -v ./...
